services:
  - type: web
    name: sorteos-csv
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CSV_PATH
        value: sample.csv  # Cambia a tu ruta real en el repo (p.ej., data/participantes.csv)
      - key: CSV_SEP
        value: ","
      - key: CSV_ENCODING
        value: "utf-8"
